# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "oCcHm7dhaaxrkxvTlUGjfB+7EDf/lP+bMmdZxrlEOTDZfN7XUUqb5es0YLgVPqA3wwpKF+nzg4PP9nI2bv7obkuagGARPVmzupkTqYJaQ9+DRQRI8sjd7UY0bEjF8AjlIyWdVg9pr+DkkANk8cpVpGVxUdja7FqQaRO3IwKQsdhDS+6N4SPd+G36Uc92lD2nn3V3ENuvvHr+twVqGTcv7QF/F9I6knwTQ6Ri7TxTvTtNRiScxP/Fo4YFxnjBdH/T96G+rbU0wVZeLwSScEhWPEgKA4vA5nvNPId78qr+aXj/s4oR61xRZIHYfcMDkLhqFGIozu+xRu84LpXwsh28XPmk9AcZq0/nQVMCZSf69+r9Ospbr2kiuo75s+frOZUiytJujjXJOSMjJXAu3LUA6681Ssr8bbic2dI/QA+Fk/SK+UsUeH50TCcJ1e+g6r3/xqYI3K0PdGp/rcDWrHbY5mkFN/0u3ReAYffj+/DGCoY5jbKxJfXaiQ7g1G3iO2Z45J/m3AaHHzxQ94jIMg4CDIfzNssiXavmP4gb/2rRK5uyj9ZLve18Orf1ojNXoFT978l4o2P8bD7ndIh8sF3uimgupzXiAydWOLqOl+yBB3rlBTn3dOzEDkH7zjJbsnw3dJGpVSIgm4xsom3DGEE1LbINDmdSVyiVQZlsJlUOiFE="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
