travis:
  secure:
    BINSTAR_TOKEN: oCcHm7dhaaxrkxvTlUGjfB+7EDf/lP+bMmdZxrlEOTDZfN7XUUqb5es0YLgVPqA3wwpKF+nzg4PP9nI2bv7obkuagGARPVmzupkTqYJaQ9+DRQRI8sjd7UY0bEjF8AjlIyWdVg9pr+DkkANk8cpVpGVxUdja7FqQaRO3IwKQsdhDS+6N4SPd+G36Uc92lD2nn3V3ENuvvHr+twVqGTcv7QF/F9I6knwTQ6Ri7TxTvTtNRiScxP/Fo4YFxnjBdH/T96G+rbU0wVZeLwSScEhWPEgKA4vA5nvNPId78qr+aXj/s4oR61xRZIHYfcMDkLhqFGIozu+xRu84LpXwsh28XPmk9AcZq0/nQVMCZSf69+r9Ospbr2kiuo75s+frOZUiytJujjXJOSMjJXAu3LUA6681Ssr8bbic2dI/QA+Fk/SK+UsUeH50TCcJ1e+g6r3/xqYI3K0PdGp/rcDWrHbY5mkFN/0u3ReAYffj+/DGCoY5jbKxJfXaiQ7g1G3iO2Z45J/m3AaHHzxQ94jIMg4CDIfzNssiXavmP4gb/2rRK5uyj9ZLve18Orf1ojNXoFT978l4o2P8bD7ndIh8sF3uimgupzXiAydWOLqOl+yBB3rlBTn3dOzEDkH7zjJbsnw3dJGpVSIgm4xsom3DGEE1LbINDmdSVyiVQZlsJlUOiFE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
