travis:
  secure:
    BINSTAR_TOKEN: Ir5b/a8MBnM/d/bm+M4dGWgAzTCv8sjx8fmpgJ6vyYS/FzgZ0EWrvg9R2RN+l0LiZMzPyElAOzx2nKGlp8CTLB2s/e6SEMfA8ziFRyZmXDl4IOcYsRfhNTX9OzdnFQiMWFHs59a9SXidrnv+CTqdfYblAf61m03zBtD0+QTLcQ6grtmE8gJFwe6u7NTDRs8AzUqxDwd9Z52oEaBgkCPsssKv1qfB85yDEkk7Eo8/fOBHxmG0vSfysbUUgfYJ4ZK42iCSTRZ/NiiGN5A32UltEqgqti4W8PgyctVMV2HewU1Wwh+oJiCMOhFQ2Xy5Fyf8f+SwpsfB9SbOpNqtA5qSeGnr8Yop65rWeuKOlD0Y+78Lc5DgJXeEjhN4ZmqtYmx5PfOaYAe37xyqqfoEbFNSl6bmYiJCoP7+48KEwPB+wm6Fg5hIJ4/sbzyT5wEo4QmxRKxomHyHBKbkSmYLO0ypsM3L238fhGKVysdNTDoh+LPIksKqJhBAPFCUQmuN+oCuM7Q2VfUPs1JrpGH+uy+h+bGnpHa26lv9eU8wdhA/omOvM/qEpGBzTMXO+gKzUGgKczK9w1ZHpc6tsi6XtvlUwHIir0B8kznSK6rAqyvJVK2DCJ1Xh7c1Qn94rKUjt7btA0FZIyYmWfHhKeU1IMdV+a1DRvGuEgNr7WbZwmAaxsQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
